### ISSUE TITLE
Always getting the Same Value for Perlin2 Noise

### ISSUE THREAD

**Issue by timlyo** [bjz/noise-rs#101]
I'm not sure what I'm doing wrong but I always seem to get the same value for perlin noise.

```rust
extern crate noise;

fn main() {
    let seed = noise::Seed::new(5);
    for x in 0..10{
        let noise = noise::perlin2(&seed, &[x as f32, 0.0]);
        println!("{:?}: {}", x, noise);
    }
}
```

gives:

```
0: 0.056165796
1: 0.056165796
2: 0.056165796
3: 0.056165796
4: 0.056165796
5: 0.056165796
6: 0.056165796
7: 0.056165796
8: 0.056165796
9: 0.056165796
```

Changing `let seed = noise::Seed::new(5);` to `let seed = noise::Seed::new(6);` gives the exact same output. What am I doing wrong?

**Comment by Aatch** [comment]
This is expected. The way the algorithm works makes the corners always be 0, though the current release adds a small constant to it, the code in the master branch actually returns 0 for all integer points. This is just an artifact of the way the noise algorithm works. 

Your samples are too far apart. Without knowing more about what you are trying to achieve, I can't help much more, but for example if you sample 10 points from (0, 0) to (1, 0), then you'll get a set of different answers. I will say that using a single perlin noise function is quite uncommon, and that normally people use multiple layers sampled at different frequencies.

**Comment by bjz** [comment]
Yes, putting some brownian motion on it will help greatly!

**Comment by timlyo** [comment]
I'm trying to generate a 2d array of noise to be used as a height map for a game. This seems to work ok:

`let noise_value = perlin2(&noise_seed, &[x as f32/256.0, y as f32/256.0]);`

**Comment by bjz** [comment]
How about adding some brownian noise to it? That should make things rougher :)

**Comment by timlyo** [comment]
I might give that a try if this isn't enough alone. I'm just using it as an initial random map so I'm going to apply other functions to simulate erosion etc.
