### ISSUE TITLE
Rename Seed module to PermTable

### ISSUE THREAD

**Issue by Razaekel** [bjz/noise-rs#116]
The name Seed for this module had been bugging me for a while, and I couldn't put my finger on why, until I sat down, read through earlier commits for it, and realized that it really just contains the permutation tables needed for gradient noise generators like Perlin or OpenSimplex.

I think this module should be renamed to either PermTable or PermutationTable, to be more explicit about what it is. It would still take a seed value for input, but it's not really a seed itself. it just uses the inputted seed value to randomized the permutation table that it contains. Additionally, I think that the perlin and opensimplex noise generators should be changed to take a uint value for their seed, and internally use it to get the permutation table, instead of providing the table itself to those generators. Essentially, Seed/PermTable should be a internal implementation detail, not something that's exposed as part of the API.

**Comment by phoenixenero** [comment]
I assume in doing so we'll have to re-calculate the permutation table (or at least the values for current and neighboring cells) for each call to the noise function? That would lower the performance quite a bit.

Unless we use a lazy evaluation library like [rust-lazy](https://github.com/reem/rust-lazy) to store the permutation table as it is generated?

**Comment by Razaekel** [comment]
With the way the code is set up right now, there's no struct for Perlin/Brownian/etc. to store objects in. In which case, it looks like it would end up regenerating the permutation table every time the noise function is called. There are some alternatives to lazy evaluation, like storing the initial seed in the Seed struct, and then comparing the passed-in seed to the stored seed, and if they're the same, carry on, otherwise if they're different, regenerate the table.

I was really thinking in terms of the noise modules that I've been working on however(see #104), where each module is a struct storing values, in which case they would be able to store either the PermTable object or the permutation table itself as a [uint], thereby only needing it to be generated when the struct is generated. This would also make it easier down the line to chain the modules, since we'd just pass down a uint instead of a &Seed.

**Comment by phoenixenero** [comment]
Ah that would make sense.

**Comment by bjz** [comment]
:+1: for the rename. I would go with `PermutationTable` personally, if it is going to be an implementation detail.

**Comment by phoenixenero** [comment]
Or `PermTable` for shortness.
