### ISSUE TITLE
Playform terrain generation is broken

### ISSUE THREAD

**Issue by bfops** [bjz/noise-rs#75]
[Playform](https://github.com/bfops/playform)'s terrain generation using `noise-rs` is broken since ee454feda924ff646b8e5bb0d3a6ca6fcb5e08de. At e584d66b605765624b6a02107933280bc16cc5e5 it looked like this: ![](http://i.imgur.com/Nm2FezX.png)

At latest (c9a4c235570a6c4085df31e38ab3f19cd7d5dc46), it looks like this: ![](http://i.imgur.com/JDjOkMQ.png)

**Comment by bjz** [comment]
Yeah, I have been hving this issue too - glad it is not just me. Sorry that I broke it :/

**Comment by bjz** [comment]
I incorrectly transcribed the `frac1` stuff (fixed by @amaranth in #69), so there could be another issue lurking in there. I can look at it tonight, but you are free to vet it to see if the are anymore issues and send a PR.

**Comment by Cifram** [comment]
To aid in debugging this, I'd like to understand why this shows up in your terrain, but not in the images generated by the examples. So, which noise functions are you using, and in what arrangement? And does this occur equally over all parts of the noise function, or possibly just in the negative regions? (It occurs to me that our examples start at 0,0 and go positive from there, so we wouldn't see any errors in the negative direction.)

**Comment by bfops** [comment]
z = 0 definitely seems discontinuous (it's the large ridge to the right in the second picture). I'm not sure what the full set of conditions is (e.g. I'm not sure where that smaller ridge in front of the player in the second picture comes from).

**Comment by Cifram** [comment]
Is this just raw perlin2 used as a heightmap, or is it Brownian2 with perlin2, or something more complicated?

**Comment by bjz** [comment]
I wonder if its:

~~~rust
let whole0 = math::map2(*point, math::cast);
let whole1 = math::add2(whole0, math::one2());
~~~

I don't specify the type I am casting to, and I have no ide where it would be inferred from... maybe it should be: `math::map2(*point, math::cast::<_, i32>);` or something?

**Comment by bjz** [comment]
Oh wait dw - it should be fine - its getting it from the calls to `gradient`.

**Comment by Cifram** [comment]
I can't poke this right now, since I'm at work, but I'd recommend moving the examples to cover the range [-512,512), instead of [0,1024). This is probably good practice anyway, because some mathematical behaviors will shift with negative inputs, and it's easy to not account for them correctly. I suspect that's the case here.

**Comment by bfops** [comment]
Oh yeah sorry, I'm not using raw perlin2, I'm using:

        Brownian2::new(perlin2, 2)
        .frequency(1.0/64.0)
        .persistence(1.0/16.0)
        .lacunarity(8.0),

**Comment by amaranth** [comment]
We're passing *point to math::cast now instead of the floored values? Does cast floor or round?

**Comment by bjz** [comment]
@amaranth No clue, but that could be the problem.

**Comment by bjz** [comment]
So you think:

~~~rust
let whole0  = math::map2(*point, math::cast);
~~~

Should be:
~~~rust
let whole0  = math::map2(floored, math::cast);
~~~
?

**Comment by amaranth** [comment]
I think so, pretty sure we broke negative values again there. That's why we didn't notice in the examples.

**Comment by bjz** [comment]
Ah, awesome. I can have a PR out this evening.

**Comment by bjz** [comment]
@bfops can you confirm that #77 fixed this for you?

**Comment by bfops** [comment]
Yup, works great now! Thanks everybody for the quick turnaround time :) ![](http://i.imgur.com/spC7ne2.png)

**Comment by bjz** [comment]
No worries, glad we could be of assistance!
